### ISSUE TITLE
Not working in ruby 2.3.0

### ISSUE THREAD

**Issue by Spandana-Sai** [toy/image_size#11]
Can you please help out. Imagesize is  not woking with ruby 2.3.0
[1] pry(main)> open("#{thumb_nail['url']}", 'rb') do |fh|
[1] pry(main)*   data = fh.read 
[1] pry(main)*   p ImageSize.new(data).size 
[1] pry(main)* end  
[nil, nil]
=> [nil, nil]
But in ruby 1.8 the output is as follows for the same image:
[7] pry(main)> open("#{thumb_nail['url']}", 'rb') do |fh|
[7] pry(main)*   data = fh.read 
[7] pry(main)*   p ImageSize.new(data).size 
[7] pry(main)* end  
[1280, 720]
=> nil

**Comment by toy** [comment]
ruby 2.3.0 is in the list of rubies tested on travis, so it should be something more specific.
Can you try to run same code with some other image?
Or is it possible for you to share the image/url?
Also I can suggest to not read the whole file, but use `fh` directly: `ImageSize.new(fh).size`. Or even `ImageSize.path("#{thumb_nail['url']}").size`.

**Comment by Spandana-Sai** [comment]
Thank you for response :). Two points
1. thumb_nail in my code is an _http url_ so I think path will not work, correct me if I am wrong
**Example**
 p ImageSize.path('http://www.rubycgi.org/image/ruby_gtk_book_title.jpg').size
NoMethodError: undefined method `path' for ImageSize:Class
from (pry):17:in `block (2 levels) in <main>'

2. Please find the image/url and examples illustrated in both ruby versions
**Example 1** - Ruby 2.3.0
[7] pry(main)> RUBY_VERSION 
=> "2.3.0"
[9] pry(main)> open('http://www.rubycgi.org/image/ruby_gtk_book_title.jpg', 'rb') do |fh|
[9] pry(main)*   data = fh.read  
[9] pry(main)*   p ImageSize.new(data).size  
[9] pry(main)* end  
[nil, nil]
=> [nil, nil]

**Example 2** - Ruby 1.8
[7] pry(main)> RUBY_VERSION 
=> "1.8.7"
[9] pry(main)> open('http://www.rubycgi.org/image/ruby_gtk_book_title.jpg', 'rb') do |fh|
[9] pry(main)*   data = fh.read  
[9] pry(main)*   p ImageSize.new(data).size  
[9] pry(main)* end  
[101, 128]
=> nil

**Comment by toy** [comment]
As I use open on url, I've assumed that you are using `open-uri`, so it should work with `ImageSize.path`.
You've got a `NoMethodError` for `path`, which suggests that you may be using an outdated version of `image_size`. Which version of `image_size` are you using? `ImageSize.path` is available from v1.1.0 - https://github.com/toy/image_size/blob/v1.1.0/lib/image_size.rb#L43.

Following code works for me in these rubies: 1.8.7, 1.9.3, 2.0.0, 2.1.8, 2.2.4, 2.3.0, jruby-1.7.24
And outputs three times `[420, 420]`

```ruby
require 'rubygems' # for ruby 1.x
require 'image_size'
require 'open-uri'

p ImageSize.path('https://avatars0.githubusercontent.com/u/14251487?v=3').size

open('https://avatars0.githubusercontent.com/u/14251487?v=3', 'rb') do |fh|
  p ImageSize.new(fh).size
end

open('https://avatars0.githubusercontent.com/u/14251487?v=3', 'rb') do |fh|
  data = fh.read
  p ImageSize.new(data).size
end
```

**Comment by Spandana-Sai** [comment]
Hey! I am using older version.. Thank you so much Solved :+1:

**Comment by toy** [comment]
Great!
